### ISSUE TITLE
ReferenceError: React is not defined

### ISSUE THREAD

**Issue by nkrmr** [Silind-Software/direflow#103]
**Describe the bug**  
I'm trying to integrate the build **direflowBundle.js** to a nextjs app and i have this issue **ReferenceError: React is not defined** on log.

**To reproduce**  
1. Install 'yarn'
2. Open 'yarn dev'
3. Build 'yarn build'
4. I copied the build file into my project and i import it with  
```javascript
<script src="/static/direflowBundle.js"></script>
```
but i have **ReferenceError: React is not defined** error

**Expected behavior**  
I want my web components to display 

**Package Manager:**  
To install Direflow, I used yarn

**Screenshots**  
<img width="646" alt="Screenshot 2020-03-18 at 12 19 57" src="https://user-images.githubusercontent.com/686395/76955748-0a84ec80-6913-11ea-835c-c312f5d85bd7.png">

**Additional context**  
May be it's because i tried to integrate the build into a nextjs app

**Comment by Silind** [comment]
Hi @nkrmr 
Thank you for creating this issue.

Yes, nextjs may very well be the cause of this problem.
Direflow Components cannot be serverside rendered, or be part of serverside rendered markup product. Both the React modules and the Web Component polyfills are lazyloaded and not included in the `direflowBundle.js` file.

You may want to try following the steps in [this comment](https://github.com/Silind-Software/direflow/issues/86#issuecomment-592940718), in order to include it all in the bundle.
Bundle size will be significantly larger, and it may still not work with serverside rendering.

But give it a shot :+1:

**Comment by nkrmr** [comment]
Hi @Silind 
I'm trying on another stack without nextjs only on a simple HTML page and i have the same issue

Best regards

**Comment by Silind** [comment]
Ok, then somethings is clearly wrong.
I'm gonna hit you up on Slack and try to help you :slightly_smiling_face:

**Comment by Silind** [comment]
Fixed in version 3.4.4 :+1:

**Comment by justinlnx** [comment]
What's the actual fix for this problem. I'm also getting the same error after loading the compiled direflowBundle.js into an angular project.
