### ISSUE TITLE
Material-UI makestyles invalid CSS

### ISSUE THREAD

**Issue by saraivinha85** [Silind-Software/direflow#105]
**Describe the bug**  
Using makeStyles generates invalid CSS

**To reproduce**  
Use material-ui makeStyles and withStyles to inject as props the CSS.

**Expected behavior**  
The generated CSS is valid

**Screenshots**  
[Screenshot](https://pasteboard.co/IZWgkdI.png)

**Comment by Silind** [comment]
Hi @saraivinha85 
Thanks for creating this issue.

Can you provide a reproducible example on a GitHub repo?
That would make it very easy for us to debug the problem.
Thanks in advance.

**Comment by saraivinha85** [comment]
Hi. Sure, take a look:
https://github.com/saraivinha85/direflow-MUI-makeStyles-bug

It just renders "hello" to the screen but the background should be red.

**Comment by Silind** [comment]
Awesome, thank you sir!
We're working on this problem as we speak.

**Comment by Silind** [comment]
Hi @saraivinha85 
This issue has been partially fixed.

Using the `withStyles` HOC from material-ui becomes unstable.
I can tweak your example to work, but it's not recommended to use the HOC.

If you instead use the hook API as explained [here](https://material-ui.com/styles/basics/#hook-api), everything works great :smile: 

Working example based on your repository:
```javascript
import { makeStyles } from '@material-ui/core/styles';

const App = () => {
  const classes = styles();
  return <div className={classes.root}>Hello</div>;
};

const styles = makeStyles({
  root: {
    backgroundColor: 'red',
  },
});

export default App;
```

**Comment by saraivinha85** [comment]
Thanks for the fix, but this solution does not work if I have a class component instead of a hook.

**Comment by Silind** [comment]
@saraivinha85 Correct.
However, you can inspect the DOM and see that a jss-tag with styles get applied, but the naming is incorrect. You can read off the classnames and see the pattern, and then add it as a string instead of referencing it via props. But it's definitely not very elegant, I agree.
The problem with the HOC becomes even worse when using the inbuilt `Styled` wrapper component, or the `withStyles` HOC that ships with Direflow.

For now, I'd recommend you use the hook API instead.
We will look into a fix for this at a later point.

**Comment by saraivinha85** [comment]
@Silind Unfortunately that's not an option for me :(

**Comment by Silind** [comment]
I understand that transforming class components into functional components often entails a lot of reimplementation.

We are sorry for the inconvenience 😞
