### ISSUE TITLE
Does not possible to create multiple bundle

### ISSUE THREAD

**Issue by supproduction** [Silind-Software/direflow#11]
I have created second component. Added entry points to the webpack as `entry: ['./src/index.tsx', './src/App2/index.tsx'],` tried to bundle it and had next error
`DireflowComponent.js:63 Uncaught DOMException: Failed to execute 'define' on 'CustomElementRegistry': this constructor has already been used with this registry`

**Comment by supproduction** [comment]
Does is it possible to add multiple entries or compile multiple components via one command?

**Comment by Silind** [comment]
Hi @supproduction 
Thank you for creating this issue.

Yes, it is indeed possible - there is a specific setup you need to use, in order to bundle multiple components together.
It's done by creating a _Direflow Project_ using the command `direflow create -p`.
This will bootstrap a project for you, and you can now add components to this project by using the command `direflow create` inside the project directory that is created.

A _Direflow Project_ offers you several other benefits besides enabling you to bundle multiple components together.

You can read a full guide to get started here:
https://direflow.io/direflow-project

**Comment by supproduction** [comment]
But in this case `Direflow` is creating new project for me. For instance I have about 70 modules with independent components, it's locate in the different folders and I need group all this files in the one build. Is it possible to compile all this components from different modules in one bundle like entries array in webpack?

**Comment by Silind** [comment]
Yes, that is exactly what the Direflow Project is meant to handle.
I suggest that you create a new Direflow Project using `direflow create -p`, and then create an empty folder called `direflow-components` in the root of your new Direflow Project.
Then copy your Direflow Components into this folder, and now run `yarn build`.
This will automatically detect all Direflow Components in the `direflow-components` folder and  bundle them together.

In the way that you are doing it now with the structure:
`['./src/index.tsx', './src/App2/index.tsx']`
you are nesting one Direflow Component in another, which is why Webpack gets confused and thinks you are trying to include the same one twice.

If you don't want to use a Direflow Project, alternatively you can do the whole thing manually:
"Flatten" your folder structure so that you don't have multiple Direflow Components nested into each other. (You'll have to do this either way).
Build them seperately using `yarn build` on each individual Direflow Component.
Now setup a custom Webpack that bundles all these `componentBundle.js` files together using the entry property.
.. However, I would definitely recommend using Direflow Project - you get a much slimmer bundle, and a more performant setup :slightly_smiling_face:

**Comment by supproduction** [comment]
I have tried do this way and I have got an error. https://prnt.sc/q265q4 . Main index.tsx is empty, all components have own registration. Could you help me what am I doing wrong? 

Our framework has over 200 modules with each own controller and own presentation.
For now we want to move all our modules some compiler/framework which will give us opportunity to transform our components to the web components. I've already investigate (stencil, svelte, lit element) and almost all of them have big cons for us - they don't supprort component inheritance. Your solution is perfectly copes with this.
 
We have control over each component library each with its own backend dev environment and we look for a way to compile all UI at once without tearing apart each repository. That's why we need one bundle which will be collect from one place via one npm command from the root one of our project, and it should sniff all our modules to detect custom elemnt, that's why we also need entry points support. Build them seperately using `yarn build` on each individual `Direflow Bundle` isn't a solution for us.

So I have a question, are you planning to work on supporting entry points?

**Comment by Silind** [comment]
Ahh ok, I understand your situation better now.

Well, the entry is fully supported.
The Direflow Components are using a modified version of the webpack.config that ships with [react-scripts](https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/config/webpack.config.js) (from create-react-app).
In the _direflow-webpack.js_ file, you are able to tweak this in anyway you want, so this can definitely be done with a bit of work.

If you use webpack.config from create-react-app as a reference, and then go into the _direflow-webpack.js_ file and do something like this:
```javascript
const webpackConfig = require("direflow-component/config-overrides");

module.exports = (config, env) => {
  const configOverride = webpackConfig(config, env);

  // Tweak configOverride here ...

  console.log(configOverride);

  // Stop server from starting ...
  throw Error('stop');

  return {
    ...configOverride
  };
};
```
...And then do `yarn build` / `yarn start`, you will be able to see the output of the config that is used for the build. It may be easier to debug this way.

If you are not able to solve this, then hit me up on contact@silind.com.
Then I will try to help your team find a good solution to this problem :slightly_smiling_face:

**Comment by supproduction** [comment]
Thanks, I'll try,  you can close this issue in that case 🙂

**Comment by supproduction** [comment]
Thanks, I am going to close this issue in that case 🙂
