### ISSUE TITLE
Place css files at the top of the component, when defined in plugins

### ISSUE THREAD

**Issue by yananym** [Silind-Software/direflow#137]
**Is your feature request related to a problem? Please describe.**  
We have a heavy css library that we include in each component. we use it as a Direflow plugin. This CSS file takes some time to load, and since it is included at the and of the component, it is visible on the screen (css flickers and assembles in few ms)

**Describe the solution you'd like**  
If you could separate plugins that need to be injected the the top of the component (like css files) and those at the end (like js modules) this would help our perceived performance a ton

**Describe alternatives you've considered**  
we would have to manually place a <link> tag with our css at the top of each component

**Comment by Silind** [comment]
Hi @yananym 
Thank you for creating this issue :slightly_smiling_face: 

I will have to kindly ask for some clarification on this feature request.

When you say that you use the css library as a Direflow plugin, I assume you are using the `external-loader` plugin to apply a css file? Is that correct?

If that is the case, I'm a little confused with what you mean by 'the top' and 'the end' of the component?
The `external-loader` plugin always adds the style into a separate `span` element which is prepended into the shadow root, __before__ the app.
Additionally, js-files are always added to the `head` of the host application and is automatically checking for duplicates.

We are adding two new options in the `external-loader` plugin.
1. an option to always inject into the `head` of the host application, even for styles.
2. providing a callback function that will fire, once the resource is fully loaded.

Do you think any of the above will solve your problem?
Otherwise, could you be a bit more specific about what you want to achieve? :blush:

**Comment by Silind** [comment]
These changes is included in v. 3.4.14
PR: https://github.com/Silind-Software/direflow/pull/140

See more on our webpage:
https://direflow.io/plugins#external-loader
