### ISSUE TITLE
react-fontawesome visual issues

### ISSUE THREAD

**Issue by mperazac** [Silind-Software/direflow#14]
Hi!

I am trying to use [React FontAwesome](https://github.com/FortAwesome/react-fontawesome) library in my project.
As this library uses SVG to display the icons, each icon displays really big.
This does not happen in a create-react-app application.
I see your comment regarding SVGs in https://direflow.io/additional, but I do not know how it applies to this library.

Can you please assist?
Thanks again!

**Comment by mperazac** [comment]
I think is the same issue as in https://github.com/Silind-Software/direflow/issues/15. So I am closing this one to track just one question/issue.

**Comment by wildfalcon** [comment]
I seem to have found a workaround for this

In your react component add the code:
```
import { library, icon } from '@fortawesome/fontawesome-svg-core'
import { faEdit, faTrash } from '@fortawesome/free-solid-svg-icons'

library.add(faEdit, faTrash)

const svgIcon = (iconName) => {
  const iconObject = icon({ prefix: 'fas', iconName: iconName })
  return (
    <>
      <span className="icon" dangerouslySetInnerHTML={{__html: iconObject.html[0]}}></span>
    </>
  )
}
```

Then wherever you're setting your css or scss for the component add this:
```
span.icon svg {
  height: 1em;
}
```

Then in your render method you can draw an object with
```{svgIcon('edit')}```

Obviously a bit of a hack, but it does work

**Comment by kelvinwongg** [comment]
Hi! I ran into the same problem. Haven't tried the method by @wildfalcon but the @mperazac give hints that is caused by the font-awesome css being injected to the <head> element, which make it unavailable to the Shadow DOM of your Web Components. My workaround to this is simply **disable the shadow dom** of my components which using Font Awesome:

In the index.js of your component:

`
export default DireflowComponent.create({
	component: Card,
	configuration: {
		tagname: 'card',
		useShadow: false,
	},
	plugins: []
});
`
