### ISSUE TITLE
Redux example

### ISSUE THREAD

**Issue by Stevemoretz** [Silind-Software/direflow#143]
Hi since I couldn't find anything in the issues I'm going to ask this here.Would anyone tell me if it supports redux between different webcomponents?If yes please provide an example.Thanks.

**Comment by Silind** [comment]
Hi @Stevemoretz 

Yes, you can definitely use Redux across different Web Component, but it may work a little differently than you're used to with React.

You want to use the 'regular' Redux as described here: https://redux.js.org/introduction/getting-started

In order to make the Web Components share the store, you need to hook up the Web Components with your store, rather than the underlying React app.
You do that by hooking into the DOM Elements of your Web Components as described here: https://direflow.io/get-started#access-the-dom-element

Check out this working example where two Direflow Components are sharing data via Redux:
https://codesandbox.io/s/redux-example-olkjn

**Comment by Silind** [comment]
I added an example on the website as well:
https://direflow.io/guides-and-tips#direflow-and-redux
