### ISSUE TITLE
React-Select library issues

### ISSUE THREAD

**Issue by mperazac** [Silind-Software/direflow#15]
Hi again,

I am also using react-select in my project.
I seems that it build its styles with styled-components internally.
When I load my app with a react-select element, it just looks like a mess. Seems that the styles are not being picked up.
Any idea what could be happening here? 

Thanks!!

**Comment by mperazac** [comment]
I get what the issue is. React-select insert its css styles into the <header> tag of the html page.
As our web component is isolated from these styles, then it can't pick them up... Hmm so, how can this be sort out?

**Comment by Silind** [comment]
Hi @mperazac 
Thank you for creating this issue.

You are right, styled-components will inject the styles into the `head` of the html document, making it unavailable for the scoped content in the shadow root.
You can use the styled-components plugin with Direflow, because the plugin will reroute the styles to be injected inside the shadowed scope instead of the `head`.
However, using styled-components as part of a third party dependency will not work at the moment.

Let's keep this issue open, and I will look into a nice solution at some point - but for now, this is unfortunately not supported.

**Comment by mperazac** [comment]
Thanks for the response, @Silind.

Just in case someone else have this problem. There is a workaround for this particular case of react-select here: https://github.com/JedWatson/react-select/issues/3680#issuecomment-532719847.

However, it would be nice that Direflow provides a way to manage these cases. 

Thanks again!

**Comment by Silind** [comment]
I'll take [the above](https://github.com/Silind-Software/direflow/issues/15#issuecomment-563352971) as the accepted answer for this issue specifically.
I'm gonna close it for now and address the situation with styled-component as a part of third party more generally later.
