### ISSUE TITLE
Event nesting in the three

### ISSUE THREAD

**Issue by ScreamZ** [Silind-Software/direflow#156]
Hello, not sure if it's a bug that why I'm asking it.

I would like to use a custom event emitter with `const dispatch = React.useContext(EventContext);`

Can I emit an event from a nested component, or should it be at the component register by direflow directly? And I should bubble it on my own to it? The doc isn't clear on that

Thanks,
Regards

**Comment by Silind** [comment]
Hi @ScreamZ

You can dispatch the event from anywhere you want in the React component tree, when using `EventContext`.
You don't need to worry about bubbling since the event will actually be emitted from the Custom Element, and not React.
The 'dispatch' function just "hands over" the event to the Custom Element which then emits it, so it doesn't actually bubble all the way through the React component tree.

I hope it makes sense :blush:

**Comment by ScreamZ** [comment]
Perfect, I was expecting such behavior ;)
