### ISSUE TITLE
Support for Preact

### ISSUE THREAD

**Issue by martinbianchi** [Silind-Software/direflow#186]
Sometimes React is too big to create a simple web component. What is happening to me is that React bundle is greater than my widget bundle.

It would be great if  we can use all the benefits of direflow with another lib like Preact that has a lower bundle size.

**Comment by Silind** [comment]
Hi @martinbianchi 
Thanks for creating this issue.

As a default, the React bundle will not be included in the Direflow bundle but instead loaded asynchronously when the Direfle bundle is consumed.

But you are right, React needs to be loaded in order for Direflow to work.

We are looking into ways of "compiling" the Web Components using SSR, so that the React bundle can be stripped at runtime altogether, for certain use-cases.

I'll close this issue since we are already considering options :blush: 
Thanks a lot for your input.

**Comment by martinbianchi** [comment]
Thanks for the feedback @Silind and this awesome library
