### ISSUE TITLE
Project dead?

### ISSUE THREAD

**Issue by BastianMa** [Silind-Software/direflow#197]
Title says it ;-)

**Comment by JohnDeved** [comment]
the projekt is definitly not dead.
@SimonHoiberg is just very busy at the moment because of launching multiple Saas products, becoming an online developer influencer and other stuff I might not be allowed to talk about yet.
He still uses Direflow in all of his products and has, therefore, definite interest in keeping this project updated.

PRs are very welcome anytime, but because of the above-mentioned reasons, you should not expect new issues to be resolved within a very short amount of time.

**Comment by JohnDeved** [comment]
closing this since the question was answered.

**Comment by SimonHoiberg** [comment]
Thanks a lot, @JohnDeved 🙌
I don't have anything more to add.

Direflow is stable - you can start using it right away.
All necessary documentation and guides can be found on https://direflow.io

Cheers.
