### ISSUE TITLE
Component property update even if the attribute is defined

### ISSUE THREAD

**Issue by filflora** [Silind-Software/direflow#29]
**Is your feature request related to a problem? Please describe.**
Is there a special reason for disabling component property update if the same property is defined as an HTML attribute?
One can set a direflow component property when the webcomponent is defined, but there is a common use-case for defining component properties on page load (in the HTML) and changing them later (via Javascript).

**Describe the solution you'd like**
As a developer I'd like to define component attributes in the HTML and change them with Javascript so the developer experience is consistent. Other HTML elements behave the same way.

**Describe alternatives you've considered**
In case this feature is missing I need to remove and recreate the whole component in the DOM if I want an attribute to be changed.

**Additional context**
I've created a fork for testing it out and it seems that it's working:
https://github.com/filflora/direflow
Should we talk about it?

Tested here:
https://github.com/filflora/direflow-poc/tree/multiple-components-per-app
Click on the button at the bottom of the page. Currently the last component is not updating.

**Comment by Silind** [comment]
Hi @filflora 
Originally, you would set two different objects; one containing _properties_ and one containing _attributes_, and these would never intersect.
However, we learned that it appeared confusing and often unpractical to handle these two mechanisms separately, and very recently, the object with the initial values was joined, such that properties would be reflected onto attributes when possible (for primitive values).

At the same, I took a decision about the attributes always taking precedence when both defined, based on... intuition, mostly.
I guess I imagined cases where you would provide the Direflow Component with some meta functionality that could be based on setting properties - for instance in the case where two components would interact with each other - and providing the end consumer with the ability to override this using attributes. (Since they would not easily access the part of the bundle code that would set properties).

But to be honest, I believe your observation is perfectly valid. And I also think that the use case you describe is much more common than the - rather exotic - one I had imagined :sweat_smile: 

I have tested your solution from your fork, it seems to work very nicely.
You are very welcome to create a PR with these changes! :muscle: 

Thanks a bunch for the contribution! :blush:

**Comment by filflora** [comment]
Thanks @Silind! I think I wasn't fully aware of that. Could you tell me more about the two component interaction? Maybe I'm missing something.

The properties and attributes are somewhat the same in my mind. I thought attributes are behaving like initial property overrides which can be changed by script. In essence there are these use cases I could think of:

Property has no default value and is `undefined`:
```
interface IProps {
  name: string;
}

const UserProfile: FC<IProps> = (props) => {
  return (<>The name is: {props.name}</>);
};

// <UserProfile></UserProfile> --> The name is:
```

Property has an internal default value and it's a `string`:
```
const UserProfile: FC<IProps> = (props) => {

  props.name = props.name || 'Anonymus';
  
  return (<>The name is: {props.name}</>);
};

// <UserProfile></UserProfile> --> The name is: Anonymus
```

Property has an internal default value but it is overridden with an attribute:
```
// <UserProfile name="John Doe"></UserProfile> --> The name is John Doe
```

Property is set by a script to a new value (By a parent of sibling element). Since a property definition like this means extra intention.
``` 
const component = document.getElementByTagName('UserProfile');
component.name = "Jane Doe";

// The name is: Jane Doe
```

Property value is changed by the parent component and the whole web component is rerendered with a new attribute value.

If you still think the PR would be ok I'd be happy to create it. I just want to be sure :)

**Comment by Silind** [comment]
The use case I'm referring to regarding two components interaction is best explained with [this example on codepen](https://codepen.io/Silind/pen/OJJbJXE).
Here I have two Direflow Components bundled together in the same bundle.js file. 
A list of crypto coins to buy and a basket. These are interacting with each other in the way that, when an item is clicked on the list in one component, the other component updates.

This is done using Redux and the `onConnected()` capability of Direflow. [Reference](https://direflow.io/get-started#callback-when-web-component-connects).

The two components are actually communicating using the DOM Api and properties, and not using React. In this case, a situation can be considered where you would like to prevent one Direflow Component in receiving data from properties, and this could be done using an attribute that takes precedens.

**However!**
The above example is based on a real-life scenario that I was dealing with, but I actually think that the whole DOM Api / and attribute shenanigan can be avoided and calls for a better design.
Since the newer versions of Direflow is using the same React instance for multiple components, the interaction should be done through React instead.

I believe that the use cases you describe above are much more common, and the differentiation between attributes and properties should be as unambiguous as possible.

So yes, please - you are very welcome to create a PR with these changes :smile:

**Comment by Silind** [comment]
Included in [this PR](https://github.com/Silind-Software/direflow/pull/31).
