### ISSUE TITLE
Optimize the bundle size

### ISSUE THREAD

**Issue by zook-cs** [Silind-Software/direflow#30]
After building the basic component the bundle size is around 280kb, I assume it is because the bundle includes react and react-dom modules.

I suggest to make the entry bundle as thin as possible and import react and react-dom only when needed by using dynamic imports. In order to use the component I will need to include only the 
entry bundle, which is very thin, and it will load react and react-dom only if the web component is used on the page.

what do you think?

**Comment by Silind** [comment]
Hi @zook-cs 
Thank you for showing interest in Direflow and creating this issue :slightly_smiling_face: 

You are very correct - the minimum bundle size of around 280kb is mainly caused by including react, react-dom modules thus the web-component bundles / polyfills. The latter is something that we are looking into.

The idea with Direflow is, in fact, to use React to create Web Components, and the main reason for using Direflow is the ability to utilize all the niceness you get from React.
Therefore, it is of course included in the bundle.

I think you have an interesting point!
If one would like to build a rather "static" Web Component, that wouldn't need UI updates and reactiveness, it would be really nice to have a way smaller bundle size.

Do you have any good suggestions to how this could work?
Maybe using the principles of SRE (server side rendering), to create the HTML markup?
And how could the need for react be detected to dynamically import the react modules?
I think an important part of Web Components is that they can be used by providing only one single bundle, so I'm not sure how the lazy loading part would work.

I am very interested in hearing your ideas here, so please don't hold yourself back if you got something good :smile:

**Comment by zook-cs** [comment]
I have a few ideas - the easiest one is letting the option to not include react and react-dom in the web component bundle and let the containing app to load them and pass them to the web component. This way you give the power to the user and he can decide what is the best way for him to bundle and use the component.

For example, I want to use the react web component (react-wc) in an angular app:
I will make an angular component that will wrap the react-wc and in its constructor will load dynamically react and react-dom so in the html file it will pass them as properties:
```
reactWC.reactLib = React;
reactWC.reactDomLib = ReactDOM;
```

**Comment by Silind** [comment]
I definitely think your idea is very interesting.
The configuration should be set in the `direflow-config.js` file, and can be added optionally, and the React and ReactDOM modules are then simply expected to be passed as properties.

The approach is a bit more "manual", but opens for customizability for cases where performance and initial bundle size is critical.
Very nice suggestion.

I'll keep this issue open to be worked on and included in an upcomming release :+1:

**Comment by zook-cs** [comment]
thanks! I really appreciate it :)

**Comment by zook-cs** [comment]
Hey Simon, I've succeeded doing what I wanted by using webpack externals in the direflow-webpack.js
`module.exports = (config, env) => ({
  ...webpackConfig(config, env),
  externals: {
    react: 'React',
    'react-dom': 'ReactDOM',
  }
});`

**Comment by Silind** [comment]
Alright @zook-cs, awesome stuff!
Do you have a public repository somewhere with a full working example?
I'd love to see how this is working.
