### ISSUE TITLE
direflow rerenders component each time when updating one prop

### ISSUE THREAD

**Issue by hahabazinga** [Silind-Software/direflow#35]
in my project, i pass several properties like this:
```
<Echarts
    styles={styles}
    option={option}
    onChartEvents={chartEventListeners}
 />
```
but inside `Echarts` component, `props` updates one by one

![image](https://user-images.githubusercontent.com/9163478/72311411-8d918880-36bf-11ea-84d7-bcb4125e9661.png)

and i check the source codes and find the following codes:
```
 public reactPropsChangedCallback(name: string, oldValue: any, newValue: any): void {
        if (oldValue === newValue) {
          return;
        }

        factory.componentProperties[name] = newValue;

        this.mountReactApp();
      }
```
and i think direflow rerenderring the comonents after all props value updated may be better 'cause there may be dependences among this prop values

**Comment by Silind** [comment]
Hi, @hahabazinga.
Thank you for creating this issue!

Nice catch - this may actually be an issue with Direflow, indeed.
I will look into this as soon as possible 👍

**Comment by Silind** [comment]
Hi again, @hahabazinga 
I'm not able to reproduce the issue you mention.

The code snippet from the source code above detects when a property or an attribute changes on the Web Component, and projects these changes onto the React app underneath.

When you set attributes on a Web Component, you do this in the HTML file, thus setting multiple attributes on the Web Component doesn't make it re-render.
Example:
```html
<some-component componentTitle="Title" anotherTitle="Other Title"></some-component>
```
This will all be interpreted once and only cause 1 render.

If you change properties in JavaScript, on the other hand, you may get multiple renders.
Example:
```javascript
const component = document.querySelector('some-component');
component.componentTitle = "Title";
component.anotherTitle = "Other title";
```
This will cause 2 renders since there is no way of telling what is going to happen "in the future" at the first assignment of `componentTitle`.
The idea of somehow "batching" updates of properties may come in the future.

So your problem doesn't seem to have anything to do with how Direflow is implemented, or at least the code snippet from above.

Can you maybe provide more thorough reproduction steps, or send me a link to a repository I can investigate?

**Comment by hahabazinga** [comment]
@Silind ，sorry, my fault for my misleading thought. i found the reason was that i created two `<Echart />` , but they referred to the same webcomponent instance, so something unexpected happended.
Besides, the` <Echarts />` is a react component which returns `<echarts-webc ref={webCRef}></echarts-webc>` , and `<echarts-webc>` is a web component rendered by direflow.
I will look into this for a further reason.

**Comment by hahabazinga** [comment]
@Silind, sry for my misleading thought. It truns out that it is because i pass props one by one to the webcomponent. I will just close this issue. Thanks for you contribution!

**Comment by Silind** [comment]
@hahabazinga Alright, cool.
I'm glad that there is clarity about the issue now 🙂
