### ISSUE TITLE
Upgrade version of direflow

### ISSUE THREAD

**Issue by lioshi** [Silind-Software/direflow#43]
**Is your feature request related to a problem? Please describe.**  
I create a web-component with Direflow in 3.0.1, how upgrade to 3.1.0 version?

**Describe the solution you'd like**  
A description of which updates make in source code.

**Describe alternatives you've considered**  
I can re-create a web-component and paste the source code... But an easy way will be good

**Comment by Silind** [comment]
Hi @lioshi 
Thanks for creating an issue.
Just as an fyi, you can still create a blank issue when you have a question 😉 

In order to upgrade to version 3.1.0, you go to package.json.
Here, you will find `direflow-component` as a dependency. Set this to `3.1.0` and run `yarn install` and you're good to go.

If something is breaking, you may need to look into the [direflow docs](https://direflow.io/get-started) to see what may be new.

Let me know if everything works out as expected 🙂

**Comment by lioshi** [comment]
Thanks!
