### ISSUE TITLE
Split Direflow Components into multiple bundles

### ISSUE THREAD

**Issue by Silind** [Silind-Software/direflow#53]
### Feature
It should be possible to set up a build configuration that specifies different bundles for different Direflow Components.

```javascript
const buildConfiguration = {
  'some-component': {
    filename: 'someComponent.js'
  },
  'another-component': {
    filename: 'anotherComponent.js'
  },
  filename: 'remainingComponents.js'
}
```
This configuration object should somehow go in the direflow-webpack file.

> The above is just an example and is subject to change.
> This issue will be edited as this feature gets more clear.

**Comment by JohnDeved** [comment]
#### Proposal for API

## Configure
configure is done on a per-component basis.
```js
direflowComponent.create([
  {
    component: MyButton,
    configure: {
      filename: 'myButton.js',
      tagname: 'button-webcomponent',
      useShadow: true,
    },
  },
  {
    component: MyInput,
    configure: {
      filename: 'myInput.js',
      tagname: 'input-webcomponent',
      useShadow: true,
    },
  },
])
```
the 'configure' prop is not needed when using the proposed configure decorator (#57)
possible alternative when configure decorator is used:
```js
direflowComponent.create([MyInput, MyButton])
```

#### why not use `direflowComponent.configure()` to set component settings?
in my opinion, `direflowComponent.configure()` would grow too complicated in this use case, that way we would probably have to have 2 arrays that define different aspects of the web components for 2 different functions. It's, better if it was dropped in this case, or let us have a discussion.

## Start
use `direflowComponent.render()` to define what Component should be used for the `yarn start` preview.
when `yarn build` is used, that component will also be build to regular react app.

in this case, the main component App is chosen to be the preview component.
```js
direflowComponent.render(App)
```
#### why not name this function `create` and the one to configure the web components `configure`?
I think we have established this far, that the `configure` function sets global settings and that the `create` function, decides what components have to be built to be webcomponents. Doing anything other with it would just be confusing.
#### so why make a new function named `render`?
because this is a new functionality of direflow and it should be clear what it does, with no double meanings.

## Build
possible file structure after build:

![image](https://user-images.githubusercontent.com/24187269/73249965-3bb82a80-41b6-11ea-87e7-3d55b0a05b53.png)
> selected (blue) = direflow web components
> rest (white) = regular react app files

#### why build the main component (set with `render`) to a regular react app?
that way you can create a regular react app and choose a few selected components of said react app to be exported as a web component to be used in other (non-react) projects.
Also, this way it should be relatively easy to take an existing react app project and convert it to a direflow project to export some components to be used as a web component.
