### ISSUE TITLE
Is it possible to access shadowRoot when using useShadow: true

### ISSUE THREAD

**Issue by traveltek-craigb** [Silind-Software/direflow#66]
I am trying to use antd components inside my exportable component. The issue is many of antd's components render popups like dropdowns and modals outside of the virtual dom as the default code adds them to document.body.

For example I need access to be able to do:
this.shadowRoot.getElementById('target') inside App.js so I can override antd functions such as,
getPopupContainer and getCalendarContainer.

`    <Styled styles={styles}>
      <div id="app" className="app">
          <ExportableToursSearchform
            onSubmit={handleSearchFormSubmit}
            getContainer={() => document.getElementById("app")}
          />
      </div>
    </Styled>`

Currently I have document.getElementById("app") but obviously with this being inside a shadowDom it can't be found. So I was wondering if this was possible or this functionality could be added?

Thanks.

**Comment by JohnDeved** [comment]
hey @traveltek-craigb thanks for submitting this issue.
you can access the shadowdom using the following:
```js
const myComponentName = 'your-web-component'
const { shadowRoot } = document.querySelector(`${myComponentName} div`)
// ...
shadowRoot.querySelector('#app')
```

ant design's popups like models also work well with shadow root if you include the antd css outside the shadow dom as well as inside. This also fixes stuff like the button ripple and so on. if that is an option for you.
Otherwise, I would always recommend using `useShadow: false` when trying to use a UI library, these libraries are not build to be used inside a web component.
We might be able to make a workaround inside direflow to get most UI libraries working anyways in the future.

If there is anything else we could help you with, please don't hesitate to let us know :)
