### ISSUE TITLE
How to use direflow-component offline without internet?

### ISSUE THREAD

**Issue by ozakaria** [Silind-Software/direflow#86]
I'm using direflow-component to generate reusable React web-components. It seems that the generated script "direflowBundle.js" is requesting many resources from internet. I have tried to use it offline without internet but it's not working at all. So, is there any way to use direflow-component offline without connecting to internet?

**Comment by Silind** [comment]
Hi @ozakaria 
Currently, this is not an option that comes out-of-the-box since the very building blocks for both Web Components and React are asynchronously requested, as you correctly have observed.

But you are not the first to ask, so we may add this feature to an upcoming release :+1: 

You can still make it work by tweaking a bit, but there may still be buggy behavior.
But here it goes :slightly_smiling_face: 

Start by altering your `direflow-webpack.js` file. It should look like this:
```javascript
module.exports = (config, env) => ({
  ...webpackConfig(config, env),
  externals: {}
});
```
Now make sure to use the [polyfill-loader](https://direflow.io/plugins#polyfill-loader) with your Direflow Components. We want to disable lazyloading of the Web Components polyfills.  
It should look like this:
```javascript
direflowComponent.configure({
  name: 'your-component',
  useShadow: true,
  plugins: [
    {
      name: 'polyfill-loader',
      options: {
        use: {
          sd: false,
          ce: false,
          adapter: false
        }
      }
    }
  ],
  // additional plugins ...
});
```
Now, install the Web Components polyfills to your project:
```console
yarn add @webcomponents/webcomponentsjs
```
Then go to your index-file (where you configure the Direflow Components), and **at the very top of the file**, add these imports:
```javascript
import '@webcomponents/webcomponentsjs/webcomponents-bundle.js';
import '@webcomponents/webcomponentsjs/custom-elements-es5-adapter.js';
```

Now you should be able to compile your Direflow Components to also work offline :slightly_smiling_face:   
> :warning: Be aware that you will now have a significantly larger bundle size of `direflowBundle.js`.

**Comment by ozakaria** [comment]
Thank you so much, @Silind
It's working now as expected 👌🏻 !

You mentioned; there may still be buggy behavior...
What is the expected side-effect of using this methodology.

**Comment by Silind** [comment]
Glad to hear that it's working for you now :blush: 

It's hard to say. Any third party library that's also fetching things using CDN's. I know quite a few.
Also, there may be unexpected behavior from Direflow itself - I can't say exactly where, but it's not optimized for offline purposes yet, so it's possible that there may be some issues.
