### ISSUE TITLE
styled-components don't seem to render on page

### ISSUE THREAD

**Issue by otherjohn** [Silind-Software/direflow#94]
I have installed styled-components via the following steps:
yarn add styled-components
added the following to index.js
```
const direflowPlugins = [
  {
    name: "font-loader",
    options: {
      google: {
        families: ["Advent Pro", "Noto Sans JP"]
      }
    }
  },
  { name: "styled-components" }
];
```
and the following in my app.js
```
import React from "react";
import PropTypes from "prop-types";
import styled from "styled-components";

const LoName = styled.span`
  font-size: 14px;
  text-transform: none;
  font-weight: 600;
`;
...
```
```
return (
   ... 
   <LoName>John</LoName>
```
I get no css rendered, but the html does this on the page
```
<span class="sc-AxjAm fcoqxY">John</span>
```
Am I doing something wrong?

**Comment by Silind** [comment]
Hi @otherjohn 
Thank you for creating this issue - you've don everything correctly.
I verified that styled-components has broken. The reason is due to styled-component recently doing a major release: https://github.com/styled-components/styled-components/blob/master/CHANGELOG.md#v500---2020-01-13

They've introduced some changes that unfortunately broke our setup.
We will update to make Styled Components works again, asap :slightly_smiling_face: 

Thank for bringing this to our attention :+1:

**Comment by otherjohn** [comment]
Awesome, thanks for jumping on this.  I am starting a web-component that uses this.
John

**Comment by machr-ACG** [comment]
Another workaround is to set `useShadow: false` but I'm not sure how that affects the rest.

**Comment by Silind** [comment]
This issue is fixed in v. 3.4.5 :slightly_smiling_face: 
You can now use the latest version of styled-components with Direflow :+1:
